version: "3.7"

services:
  spring:
    image: jaehyeon1114/solasido:latest
    expose:
      - "8080" #expose는 컨테이너 내부 포트만 열어둠.
    container_name: spring
    networks:
      - web_network


  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - spring
    networks:
      - web_network

networks:
  web_network:
    driver: bridge